### ISSUE TITLE
Public static property 'btnZoom' error.

### ISSUE THREAD

**Issue by djeverson** [JoxieMedina/ionic2-simple-conditional-wizard#1]
I tried incorporating this plugin into my project.  I am getting a series of errors related to animations.  Any suggestion has to what the issue might be?

`[ts] Public static property 'btnZoom' of exported class has or is using name 'AnimationEntryMetadata' from external module "/Users/djeverson/workspace/projects/ath/mobile/ath-v3/node_modules/@angular/core/src/animation/metadata" but cannot be named.
`

I get these errors on each of the static properties in the animations component.

**Comment by JoxieMedina** [comment]
Hi @djeverson , can you run $ ionic info and paste the info here, please.

**Comment by djeverson** [comment]
--------------------------------

Your system information:

Cordova CLI: 6.2.0

Ionic Framework Version: 2.0.0-rc.1

Ionic CLI Version: 2.1.4

Ionic App Lib Version: 2.1.2

Ionic App Scripts Version: 0.0.36

ios-deploy version: 1.9.0

ios-sim version: 5.0.10

OS: Mac OS X El Capitan

Node Version: v4.4.7

Xcode version: Xcode 8.0 Build version 8A218a

--------------------------------

Dave Everson

On Wed, Dec 28, 2016 at 12:08 PM Darwin

<
mailto:Darwin <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi
https://github.com/djeverson
, can you run $ ionic info and paste the info here, please.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/JoxieMedina/ionic2-simple-conditional-wizard/issues/1#issuecomment-269515875
, or

**Comment by JoxieMedina** [comment]
I used to have this issue too with the rc1 and I solved updating the ionic scripts, I recommend you update to have this ionic info:
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: macOS Sierra
Node Version: v5.8.0
Xcode version: Xcode 8.1 Build version 8B62

To update the ionic scripts run `$ npm install @ionic/app-scripts@latest --save-dev` and to update to rc 3 you can modify your package.json and use the same dependencies from my [https://github.com/JoxieMedina/ionic2-simple-conditional-wizard/blob/master/package.json](package.json) , you can copy and paste in your project and delete the node_modules folder and run a fresh `$ npm install`

**Comment by djeverson** [comment]
Thanks for the suggestion - I upgraded and the error continues.  During the upgrade a lot of things broke but eventually I ended up with the following configuration.  This is one area that I don't like and get easily frustrated with Ionic/Angular...

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4-201612220408
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: OS X El Capitan
Node Version: v7.3.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by JoxieMedina** [comment]
I created a new project and doesn't give me that error, can you upgrade the Ionic CLI too: `$ npm install -g ionic` and create a new project and paste your code, and tell me if it's works.

**Comment by djeverson** [comment]
I uninstalled and re-installed everything.  Things are now working.  Thanks for your time.
