### ISSUE TITLE
Bad docs and angular animatiosn problem

### ISSUE THREAD

**Issue by quedicesebas** [JoxieMedina/ionic2-simple-conditional-wizard#10]
1. In docs, there's no instruction for import BrowserAnimationsModule
2. BrowserAnimationsModule requires to install @angular/animations, but current version fails. Was needed to install 4.1.3 version

**Comment by JoxieMedina** [comment]
@sebrojas14 pull request are welcome buddy ✌️

**Comment by quedicesebas** [comment]
Done https://github.com/JoxieMedina/ionic2-simple-conditional-wizard/pull/11
