### ISSUE TITLE
Problem with ion-toggle after step animation

### ISSUE THREAD

**Issue by quedicesebas** [JoxieMedina/ionic2-simple-conditional-wizard#12]
The ion-toggle elements in my code change after the step animation and only restore after toggle.

Before:
![image](https://user-images.githubusercontent.com/1771574/29983677-9fa2f0ba-8f1c-11e7-9966-e5e26bc39d7c.png)

After:
![image](https://user-images.githubusercontent.com/1771574/29983669-9940c1ac-8f1c-11e7-8b68-115e4a859b55.png)

**Comment by JoxieMedina** [comment]
@sebrojas14  I don't really sure what do you mean or what is your issue ¿?

_Puedes escribir en español si así te puedes expresar mejor tu problema, necesito entender bien que es lo que no funciona como esperas para poder replicar tu problema_

**Comment by quedicesebas** [comment]
@JoxieMedina, a ver explico largo. Usé el wizard, con 4 pasos, como se ve ahí. En cada paso hay componentes ion-toggle. Cómo se ve en las imágenes, como en la primera se ve el toggle normalmente, después de avanzar el paso, queda como se ve en la segunda imagen (ahí avancé y volví atrás, pero pasa lo mismo con los toggle que hay en el segundo paso desde el principio, ya que entra con transición)

**Comment by JoxieMedina** [comment]
Parece ser que hay un problema con `ion-toggle` y las animaciones, si cambias la animación en esta línea https://github.com/JoxieMedina/ionic2-simple-conditional-wizard/blob/master/src/pages/ion-simple-wizard/ion-simple-wizard.step.component.ts#L14 a `animations: WizardAnimations.none` no hay problema, creo que por los momentos eso solucionaría tu problema hasta que investigue más por qué existe ese problema con los ion-toggle

**Comment by quedicesebas** [comment]
Estaré pendiente, yo no tengo experticia en ese tema de las animaciones, peor fue lo que me gustó de este componente y que me hizo usarlo sobre usar páginas. Ojalá me des una mano.

**Comment by quedicesebas** [comment]
@JoxieMedina the problem doesnt's occurs with carousel animations
