### ISSUE TITLE
On Success Finish how can back to first step o reset component to initial state ?

### ISSUE THREAD

**Issue by togro** [JoxieMedina/ionic2-simple-conditional-wizard#13]
How can back to first step o reset component to initial state when wizard finish onsuccess ?

When  set step = 1 at end of wizard , the footer nav back to step 1 ( 7/7 => 1/7 )  , but main  content don't change from  last step (continue showing last step) 

We need that for do another wizard operation.

**Comment by hoainhan** [comment]
hi.
did you resolve that problem?
I have a issue like this, I can't reload wizard after I remove a step.

**Comment by togro** [comment]
I use this blog info :

https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

And put some like inside of call from validator:

            setTimeout(() => {                                               
                obj.stepCondition = true;
             });
