### ISSUE TITLE
Change step manually

### ISSUE THREAD

**Issue by vvalladolidIV** [JoxieMedina/ionic2-simple-conditional-wizard#15]
Hi,

I would like to can change the step programatically. Is it posibble?
I tried importing "EventEmitter" and type that: "emit(this.step + 1);" about the object but...nothing.

Thank you,
Vicente

**Comment by mubasshir** [comment]
Hi @vvalladolidIV ,
did you find solution to this?

**Comment by JoxieMedina** [comment]
In the next version update this would be easy to do
