### ISSUE TITLE
Not compatible with Angular@5.0.3 or later

### ISSUE THREAD

**Issue by fastwalker** [JoxieMedina/ionic2-simple-conditional-wizard#16]
I have been trying to implement this component into my own.  Yet, when I try to view the HTML of the component, I get "Uncaught (in promise): invalid views to insert".  Thanks in advance.

`
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.6
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 6.10.0
`

**Comment by Assdi** [comment]
had issue with angular 5.0 . the issue is with angular animation module

**Comment by JoxieMedina** [comment]
Hi @fastwalker , sorry about the late I just update the dependencies and everything works fine, can you please share more details about your issue or how to reproduce it ?
