### ISSUE TITLE
Dynamic Steps not working

### ISSUE THREAD

**Issue by mubasshir** [JoxieMedina/ionic2-simple-conditional-wizard#2]
Hi, 
First of all I would like to applaud you for making such an awesome Component.

**TL;DR: Steps not properly working in case of ngFor**

`<ion-wizard-step *ngFor="let dynamicStep of dynamicSteps"></ion-wizard-step>`
When I'm using loop for in between Steps on & clicking on next or prev fab buttons, it skips these dynamic stpes.

These pages can only be accessed by last step. Basically, steps are created properly in html but in TS, these pages are added at back, whereas I should be as per html order

In my opinion, TS file needs to handle loop/html in proper way

Kindly help.

**Comment by JoxieMedina** [comment]
Hi @mubasshir, thanks for use the component, and I will try to reproduce your issue and keep you in touch any advance

**Comment by JoxieMedina** [comment]
Hi @mubasshir I recently uploaded an update for this component which contains an example of how to use it with dynamic content, please take a look in the code of `dynamic-steps` folder.

Greetings!

**Comment by mubasshir** [comment]
Hi,
You have assumed that all steps are dynamic. But what if first and last step is static (written inside html) and middle ones are dynamic. Could try this case?
