### ISSUE TITLE
Own button that triggers next step?

### ISSUE THREAD

**Issue by nicklas669** [JoxieMedina/ionic2-simple-conditional-wizard#4]
Hello,

I am playing around with your component and thanks for making it! I was wondering if there is a way to have my own button go to the next step? I see that I need to call next() in ion-simple-wizard.component.ts but I have not been able to do this from "the outside" - I have tried my own function that calls this.evts.publish('step:next') but this was not enough.. I seem to be missing this.stepChange.emit(this.step + 1)..

Another question would be: is it possible to have a step's stepCondition = true without all the other steps having it? I would like one of my steps to have the next-button available without the user doing something first?

Thanks in advance :)

**Comment by JoxieMedina** [comment]
Hi @nicklas669 , of course you can use other way to do the next step, one way can be in the file `ion-simple-wizard.component.ts`

subscribe to a new event something like this :
````
constructor(public evts: Events) {
    this.evts.subscribe('step:ownNext', () => {
      this.ownNext();
    })
  }
````

and in the same file add this function : 
````
ownNext() {
    this.stepChange.emit(this.step + 1);
    this.evts.publish('step:next');
  }
````

So when you already added the above you can emit the new event  in the component which you use the wizard calling the next function:
````
  doStepNext() {
        this.events.publish('step:ownNext');
    }
````

It's the same for the back button, and the function of the stepCondition it's for each step the condition is set to this value, set to true if you don't need condition in every step.

To learn more about the component you can check out the new example which I just uploaded.

Greetings!

**Comment by nicklas669** [comment]
Subscribing to and publishing 'step:ownNext' worked well! Thanks.
