### ISSUE TITLE
Not working with Ionic 3

### ISSUE THREAD

**Issue by mubasshir** [JoxieMedina/ionic2-simple-conditional-wizard#5]
kindly check following post & update for Ionic 3
https://forum.ionicframework.com/t/cannot-find-name-animationmodule/84483?u=mubasshir

**Comment by jdell64** [comment]
I updated mine to ionic3... I had to do this:

run this:

    $ ionic plugin add ionic-plugin-keyboard
    $ npm install --save @ionic-native/keyboard

add this line:

    import { Keyboard } from '@ionic-native/keyboard';

inject it into the constructor:

    constructor(public evts: Events, private keyboard: Keyboard) {}

ngOnInit: 
```
 ngOnInit() {
    /**
     * Hide the wizard buttons when the keyboard is open
     */
    this.keyboard.onKeyboardShow().subscribe(() => {
      this.hideWizard = true;
    });
    this.keyboard.onKeyboardHide().subscribe(() => {
      this.hideWizard = false;
    })
  }
```

Untested at the moment.
